import {UNVISITED,VISITED,VISITING,OBSTRUCTION,MAX_ROW,MAX_COLUMN,PATH,startX,startY,endX,endY,MAZE_SPEED,SEARCH_SPEED} from '../algorithms/GRAPH_CONSTANTS'
// const UNVISITED=0;
// const VISITED=1;
// const OBSTRUCTION=2
// const VISITING=3;

export { UNVISITED, VISITED, VISITING,OBSTRUCTION, MAX_ROW,MAX_COLUMN, PATH ,startX,startY,endX,endY,MAZE_SPEED,SEARCH_SPEED}