const UNVISITED=0;
const VISITED=1;
const OBSTRUCTION=2
const VISITING=3;
const PATH=4
const MAX_ROW=20;
const MAX_COLUMN=50;

export { UNVISITED, VISITED, VISITING,OBSTRUCTION,MAX_COLUMN,MAX_ROW,PATH }